name: Test notify2222

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  check-failed-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Notify failed runs
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPOSITORIES: "isboston/appGHA,isboston/appGHA2"
          # REPOSITORIES: "ONLYOFFICE/DocSpace-buildtools,ONLYOFFICE/OneClickInstall-Workspace,ONLYOFFICE/OneClickInstall-Docs"
        run: |
          IFS=',' read -ra REPO_LIST <<< "$REPOSITORIES"

          for REPO in "${REPO_LIST[@]}"; do
            FAILS="$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/actions/runs?per_page=100" | \
              jq --arg start "$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" '[.workflow_runs[]
                  | select(.created_at >= $start and ((.conclusion? // "failure") | test("failure|failed|error|startup_failure")))
                  | select(.head_branch | test("^(main|release/.+|hotfix/.+|develop)$"))]')"

            COUNT="$(jq length <<< "$FAILS")"
            if (( COUNT > 0 )); then
              LINES="$(jq -r '[.[] |
                "\u25FB [\(.name[:29] + (if .name|length>26 then "..." else "" end))](\(.html_url)) (\(.head_branch))"
              ] | join("\n")' <<< "$FAILS")"
              RESULT+="*\u274C $COUNT FAILED | 24h | REPO: $REPO*\n$LINES\n\n"
            fi
          done

          if [[ -n "$RESULT" ]]; then
            curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -H "Content-Type: application/json" \
              -d "{\"chat_id\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"$RESULT\", \"parse_mode\": \"Markdown\", \"disable_web_page_preview\": true}"
          fi

