name: Test action for 24h

on:
  workflow_dispatch:

jobs:
  check-failed-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Notify failed runs
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_GROUP }}
          WORKFLOWS: |
            appGHA|ci-oci.yml|ci-oci
            appGHA|check-workflows.yml|check-workflows
            appGHA|check-work.yml|check-work
            appGHA2|test.yml|test
        run: |
          declare -A REPO_STATUS
          declare -a REPO_ORDER

          while IFS='|' read -r REPO WORKFLOW WORKFLOW_NAME; do
            [[ -z "$REPO" || -z "$WORKFLOW" ]] && continue
            if [[ ! " ${REPO_ORDER[*]} " =~ " $REPO " ]]; then
              REPO_ORDER+=("$REPO")
            fi
            RUNS_RESPONSE="$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/isboston/$REPO/actions/workflows/$WORKFLOW/runs?per_page=100")"
            [[ ! $(echo "$RUNS_RESPONSE" | jq -e .workflow_runs) ]] && continue
            RUNS=$(echo "$RUNS_RESPONSE" | jq --arg start "$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" '[.workflow_runs[]| select(.created_at >= $start)
              | select(.head_branch | test("^(main|release/.+|hotfix/.+|develop)$"))]')
            FAIL_COUNT=$(echo "$RUNS" | jq '[.[] | select((.conclusion? // "failure") | test("failure|failed|error|startup_failure"))] | length')
            STATUS=$([[ $(echo "$RUNS" | jq 'length') -eq 0 ]] && echo "\u26AA" || ([[ $FAIL_COUNT -gt 0 ]] && echo "\uD83D\uDD34" || echo "\uD83D\uDFE2"))
            REPO_STATUS["$REPO"]+="$STATUS [$WORKFLOW_NAME](https://github.com/isboston/$REPO/actions/workflows/$WORKFLOW)\n"
          done <<< "$WORKFLOWS"

          for REPO in "${REPO_ORDER[@]}"; do
            RESULT+="*$REPO*\n${REPO_STATUS[$REPO]}\n"
          done

          if [[ -n "$RESULT" ]]; then
              for chat_id in ${TELEGRAM_CHAT_ID_GROUP//,/ }; do
                  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                    -H "Content-Type: application/json" -d "{\"chat_id\": ${chat_id}, \"text\": \"$RESULT\", \"parse_mode\": \"Markdown\", \"disable_web_page_preview\": true}"
              done
          fi

