name: Daily Failed Actions Report

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 UTC
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
          
      - name: Run failure check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_TOKEN_REPO1: ${{ secrets.GITHUB_TOKEN_REPO1 }}
          GITHUB_TOKEN_REPO2: ${{ secrets.GITHUB_TOKEN_REPO2 }}
          GITHUB_REPO1: ${{ secrets.GITHUB_REPO1 }}
          GITHUB_REPO2: ${{ secrets.GITHUB_REPO2 }}
        run: |
          python scripts/check_failed_actions.py