name: Notify Telegram on Failure

on:
  schedule:
    - cron: "5 0 * * *"  # Запуск каждый день в 00:05 UTC
  workflow_dispatch:

jobs:
  check-build-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Получаем информацию о workflow runs за последние 24 часа
        run: |
          # Определяем период: последние 24 часа от текущего момента
          START_TIME=$(date -u -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")
          END_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Запрашиваем workflow runs с $START_TIME по $END_TIME"

          # Запрос последних 100 запусков (при необходимости можно реализовать постраничный запрос)
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" | \
            jq --arg start "$START_TIME" --arg end "$END_TIME" \
            '[.workflow_runs[] | select(.created_at >= $start and .created_at <= $end)]' > workflow_runs.json

          echo "Полученные данные:"
          cat workflow_runs.json

          # Формирование JSON с нужными полями и установкой статуса (если статус отсутствует, считаем за неудачный)
          jq '[.[] | {name: .name, branch: .head_branch, html_url: .html_url, status: (.conclusion // "failure"), triggered_by: (.triggering_actor.login // "unknown")}]' workflow_runs.json > merged_results.json
          echo "Итоговые данные:"
          cat merged_results.json

      - name: Отправляем отчёт в Telegram, если есть ошибки
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ ! -s merged_results.json ] || [ "$(jq 'length' merged_results.json)" -eq 0 ]; then
            echo "За указанный период нет завершённых сборок."
            exit 0
          fi

          TOTAL=$(jq 'length' merged_results.json)
          # Фильтруем только неудачные сборки
          FAILURES=$(jq '[.[] | select(.status=="failure" or .status=="failed" or .status=="error" or .status=="startup_failure")]' merged_results.json)
          FAIL_COUNT=$(echo "$FAILURES" | jq 'length')
          
          MESSAGE="🕒 *Отчёт за последние 24 часа*\n"
          MESSAGE+="📊 Всего сборок: *$TOTAL*\n"

          if [ "$FAIL_COUNT" -eq 0 ]; then
            MESSAGE+="✅ *Все сборки успешны!* 🎉\n"
          else
            MESSAGE+="❌ *Проблемные сборки: $FAIL_COUNT*\n\n"
            # Формируем список ошибок с данными о workflow
            FAIL_LIST=$(echo "$FAILURES" | jq -r '
              map(
                "🔹 *\(.name // \"Неизвестный workflow\")* " +
                "\n  ├ 📌 Ветка: *\(.branch // \"Неизвестная ветка\")*" +
                "\n  ├ 👤 Запустил: *\(.triggered_by // \"Неизвестный\")*" +
                "\n  ├ 🔗 [Лог](\(.html_url // \"Нет ссылки\"))\n"
              ) | join("\n")
            ')
            MESSAGE+="$FAIL_LIST"
          fi

          # Отправка сообщения в Telegram
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"$MESSAGE\", \"parse_mode\": \"Markdown\", \"disable_web_page_preview\": true}"
