name: Build packages
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing job"

      - name: Git clone my repo
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Deploy job"

      - name: Test if AWS CLI is installed
        run: aws --version

      - name: Simulate failure
        run: exit 1

  log-build-result:
    if: always()
    runs-on: ubuntu-latest
    needs: [deploy]  # Нужно, чтобы получить статус "deploy"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous results
        uses: actions/download-artifact@v4
        with:
          name: build_results-${{ github.run_id }}
        continue-on-error: true

      - name: Создаем/загружаем build_results.json
        run: |
          if [ -f build_results.json ]; then
            cp build_results.json results_tmp.json
          else
            echo '[]' > results_tmp.json
          fi

      - name: Сохраняем текущий результат
        run: |
          NOW=$(date -u +"%Y-%m-%d")
          RAW_RESULT="${{ needs.deploy.result }}"
          if [[ -z "$RAW_RESULT" ]]; then
            RESULT="failure"
          else
            RESULT="$RAW_RESULT"
          fi
          jq --arg date "$NOW" --arg status "$RESULT" '. += [{"date": $date, "status": $status}]' results_tmp.json > build_results.json

      - name: Загружаем build_results.json
        uses: actions/upload-artifact@v4
        with:
          name: build_results-${{ github.run_id }}
          path: build_results.json
          retention-days: 1
