name: Test1

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing job"
      
      - name: List current folder
        run: |
          ls -la
          pwd
      - name: Git clone my repo
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Deploy job"

      - name: Test if AWS CLI is installed
        run: aws --version

      - name: Simulate failure
        run: exit 1